name: SCION_Controller
description: A portable app for controlling the SCION device via OSC

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  file_picker: ^6.1.1
  intl: ^0.20.2
  osc:
    path: /Users/josh/src/superchromat/osc/
  material_symbols_icons: ^4.2815.0
  shared_preferences: ^2.0.18
  flutter_typeahead: ^4.1.1
  nsd: ^4.0.2
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
